services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${RATEUS_DB}
      POSTGRES_USER: ${RATEUS_USER}
      POSTGRES_PASSWORD: ${RATEUS_PASSWORD}
    ports:
      - "5433:5432" # TO REMOVE
    volumes:
      - rateus_db_data:/var/lib/postgresql/data

  spring:
    build: ./backend/core
    container_name: spring
    environment:
      BACKEND_PG_HOST: postgres
      BACKEND_PG_PORT: 5432
      RATEUS_DB: ${RATEUS_DB}
      RATEUS_USER: ${RATEUS_USER}
      RATEUS_PASSWORD: ${RATEUS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}

  nextjs:
    build: ./frontend/rateus-app
    container_name: nextjs
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs
      - spring
    restart: always

volumes:
  rateus_db_data:
