import { USER_ROLE } from "./user-roles";

export const PROFILE_COMMON_PAGE = {
  SETTINGS: "settings",
  NOTIFICATIONS: "notifications",
};

export const PROFILE_PAGE = {
  REVIEWS_SELF: "reviews-self",
  REVIEW_BRIEFS_SELF: "review-briefs-self",
  ORGANIZATIONS_SELF: "organizations-self",
  ORGANIZATION_BRIEFS_SELF: "organization-briefs-self",
  REVIEWS: "reviews",
  REVIEW_BRIEFS: "review-briefs",
  ORGANIZATIONS: "organizations",
  ORGANIZATION_BRIEF: "organization-brief",
  ORGANIZATION_BRIEFS: "organization-briefs",
  USERS: "users",
  ORGANIZATION_TYPES: "organization-types",
};

export const PROFILE_PAGE_AUTHORITIES = {};

PROFILE_PAGE_AUTHORITIES[USER_ROLE.USER] = [
  PROFILE_PAGE.REVIEWS_SELF,
  PROFILE_PAGE.REVIEW_BRIEFS_SELF,
];

PROFILE_PAGE_AUTHORITIES[USER_ROLE.OWNER] = [
  PROFILE_PAGE.REVIEWS_SELF,
  PROFILE_PAGE.REVIEW_BRIEFS_SELF,
  PROFILE_PAGE.ORGANIZATIONS_SELF,
  PROFILE_PAGE.ORGANIZATION_BRIEF,
  PROFILE_PAGE.ORGANIZATION_BRIEFS_SELF,
];

PROFILE_PAGE_AUTHORITIES[USER_ROLE.MODERATOR] = [
  PROFILE_PAGE.REVIEWS,
  PROFILE_PAGE.REVIEW_BRIEFS,
  PROFILE_PAGE.ORGANIZATIONS,
  PROFILE_PAGE.ORGANIZATION_BRIEF,
  PROFILE_PAGE.ORGANIZATION_BRIEFS,
];

PROFILE_PAGE_AUTHORITIES[USER_ROLE.ADMIN] = [
  PROFILE_PAGE.REVIEWS,
  PROFILE_PAGE.REVIEW_BRIEFS,
  PROFILE_PAGE.ORGANIZATIONS,
  PROFILE_PAGE.ORGANIZATION_BRIEF,
  PROFILE_PAGE.ORGANIZATION_BRIEFS,
  PROFILE_PAGE.USERS,
  PROFILE_PAGE.ORGANIZATION_TYPES,
];
